version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_alura
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
